<?php
/**
 *
 * @category    design
 * @package     mbemro_mobile
 * @copyright   Copyright (c) 2014 MBE MRO Catalog (http://www.mbemrocatalog.com)
 * @license     Comercial
 */
?>
<?php  $_order = $this->getOrder() ?>
<div class="row hidden-xs hidden-sm">
<p class="order-links">
    <?php  if ($_order->getTracksCollection()->count()) : ?>
        <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track all shipment(s)') ?>"><?php echo $this->__('Track all shipments') ?></a> <span class="separator">|</span>
    <?php endif; ?>
    <a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print All Shipments') ?></a>
</p>
</div>
<div class="row visible-xs visible-sm btn-group btn-group-justified">
    <?php  if ($_order->getTracksCollection()->count()) : ?>
        <a href="#" class="btn btn-default" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track all shipment(s)') ?>"><?php echo $this->__('Track all shipments') ?></a>
    <?php endif; ?>
    <a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>" onclick="this.target='_blank'" class="btn btn-default link-print"><?php echo $this->__('Print All Shipments') ?></a>
</div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
<div class="row hidden-xs hidden-sm">
<h2 class="sub-title"><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?> <span class="separator">|</span> <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print Shipment') ?></a></h2>
</div>
<div class="row visible-xs visible-sm btn-group btn-group-justified">
    <a href="#" class="btn btn-default disabled"><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?></a>
    <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>" onclick="this.target='_blank'" class="btn btn-default link-print"><?php echo $this->__('Print Shipment') ?></a>
</div>
<?php $tracks = $_shipment->getTracksCollection(); ?>
<?php  if ($tracks->count()): ?>
    <div class="row data-table tracking-table" id="my-tracking-table-<?php echo $_shipment->getId(); ?>">
        <div class="col-xs-12">
            <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_shipment) ?>','trackshipment','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track this shipment') ?>"><?php echo $this->__('Track this shipment') ?></a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6"><?php echo $this->__('Tracking Number(s):') ?></div>
        <div class="col-xs-6 no-padding">&nbsp;
                <?php
                $i = 1;
                $_size = $tracks->count();
                foreach($tracks as $track): ?>
				<span class="tracking-number">
                <?php if($track->isCustom()): ?>
                    <?php echo $this->escapeHtml($track->getNumber()) ?>
                <?php else: ?>
                    <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?></a>
                <?php endif; ?>
				</span>
                <?php if($i!=$_size): ?>, <?php endif; ?>
                <?php $i++;
                endforeach; ?>
        </div>
    </div>

    <script type="text/javascript">decorateTable('my-tracking-table-<?php echo $_shipment->getId(); ?>')</script>
<?php  endif; ?>
<h3 class="table-caption"><?php echo $this->__('Items Shipped') ?></h3>
<div class="row data-table" id="my-shipment-table-<?php echo $_shipment->getId(); ?>">
    <div class="col-xs-6"><?php echo $this->__('Product Name') ?></div>
    <div class="col-xs-3"><?php echo $this->__('SKU') ?></div>
    <div class="col-xs-3" class="a-center"><span class="nobr"><?php echo $this->__('Qty Shipped') ?></span></div>
</div>
    <?php $_items = $_shipment->getAllItems(); ?>
    <?php $_count = count($_items) ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>

        <?php echo $this->getItemHtml($_item) ?>

    <?php endforeach; ?>

<script type="text/javascript">decorateTable('my-shipment-table-<?php echo $_shipment->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php echo $this->getCommentsHtml($_shipment)?>
<?php endforeach; ?>
