<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<?php //echo $_customer->getGroupId(); ?>
<?php //echo $_customer->getCorpCompany(); ?>
<?php //echo $_customer->getCorpDepartment(); ?>
<?php //echo $_customer->getCorpDepSupervisor(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Orders waiting approval') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col />	
    <col width="1" />
    <col width="1" />	
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Made By') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>			
            <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>			
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td><?php echo $_order->getRealOrderId() ?></td>
            <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
			<td><?php echo Mage::getModel('customer/customer')->load($_order->getCustomerId())->getName();?></td>
            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td><em><?php echo $_order->getStatusLabel() ?></em></td>			
            <td class="a-center">
            <span class="nobr"><a href="<?php echo Mage::getBaseUrl().'orderconfirmation/index/view/order_id/'.$_order->getId() ?>"><?php echo $this->__('View Order') ?></a></span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('There are no new orders.'); ?></p>
<?php endif ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
