
<?php if (!isset($_POST['contact_form'])) : ?>
<!-- periodic-agreement-holder -->
<div class="periodic-agreement-holder">
	<div class="page-title">
		<h1>Contact Us</h1>
	</div>
	<div class="clear"></div>
	<div class="top_text_holder">
		<div class="clear"></div>
	</div>
	<form action="<?php echo Mage::helper('cms/page')->getPageUrl('contact-us') ?>" method="post" id="contact_us_form" name="contact_us_form">
			<!-- billing_period_terms_holder -->
			<div id="contact_us">
				
				<!-- row_holder -->
				<div class="row">
					<div class="col-xs-12 text-left">
						<span><span class="required">*</span> = Required Fields</span>
					</div>
				</div><!-- END//row_holder -->
				<!-- row_holder -->
				<div class="row">
					<div class="col-sm-3">Name</div>
					<div class="col-sm-9">
						<input type="text" id="name" name="name" maxlength="40" value="">
					</div>
				</div><!-- END//row_holder -->
				<!-- row_holder -->
				<div class="row">
					<div class="col-sm-3">E-mail <span class="required">*</span></div>
					<div class="col-sm-9">
						<input type="text" id="email" name="email" maxlength="40" value="">
					</div>
				</div><!-- END//row_holder -->
				<!-- row_holder -->
				<div class="row">
					<div class="col-sm-3">Phone</div>
					<div class="col-sm-9">
						<input type="text" id="phone" name="phone" maxlength="40" value="">
					</div>
				</div><!-- END//row_holder -->
				<!-- row_holder -->
				<div class="row">
					<div class="col-sm-3">Message <span class="required">*</span></div>
					<div class="col-sm-9">
						<textarea name="message" id="message"></textarea>
					</div>
				</div><!-- END//row_holder -->
			</div>
			<?php 
		$block = $this->getLayout()->createBlock('captcha/captcha_zend')
		->setFormId('user_create')
		->setImgWidth(230)
		->setImgHeight(50);
		$block->getCaptchaModel()->generate();
		echo $block->renderView();
		
		?>
			<div class="row">
         		  <div class="col-xs-12 cms_form_submit"><a href="#" class="btn submit-button"onclick="beforeSubmit();">Submit</a></div>
                        </div>
			<input type="hidden" name="contact_form" value="Y">
	</form>
</div>

<script type="text/javascript">
	function beforeSubmit() {
		allok = true;
		firstchecked = '';

		checkElementString('email');
		checkElementString('message');
		
		if (allok == false) {
			document.getElementById(firstchecked).focus();
			return;
		};

		if (document.getElementById('email').value.indexOf('@') == -1) {
			document.getElementById('email').focus();
		};

		document.forms['contact_us_form'].submit();
	}

	function checkElementString(elementId) {
		var element = document.getElementById(elementId);
		element.style.border = '1px solid #B6B6B6';
		if (element.value.trim() == '') {
			element.style.border = '1px solid red';
			allok = false;
			if (firstchecked == '') {
				firstchecked = elementId;
			};
		};
	}
</script>
<?php else :

	$data = $this->getRequest()->getParams();
	$error = null;
	//check captcha first
	$_captcha = Mage::getModel('customer/session')->getData('user_create_word');  
	if ($_captcha['data'] != $data['captcha']['user_create']) {  
	    $error = 'Please provide correct captcha value.'; 
	}
	if (!$error) {
		$body = "Contact Request\n\n";
		
		$body .= (isset($data['name'])) 			? "Name: ".$data['name']."\n" : "";
		$body .= (isset($data['email'])) 			? "E-mail: ".$data['email']."\n" : "";
		$body .= (isset($data['phone'])) 			? "Phone: ".$data['phone']."\n" : "";
		$body .= (isset($data['message'])) 			? "Message: ".$data['message']."\n" : "";

		$mail = Mage::getModel('core/email');
		//$mail->setToName(Mage::getStoreConfig('trans_email/ident_support/name'));
		//$mail->setToEmail(Mage::getStoreConfig('trans_email/ident_support/email'));
		$mail->setToEmail("customerservice@mbemrocatalog.com");
		// $mail->setToEmail("lpuroll@psmicorp.com");
		//$mail->setToEmail("sosingus@gmail.com");

		$mail->setBody($body);
		$mail->setSubject('Contact Form Request');
		$mail->setFromEmail($data['contact@mbemrocatalog.com']);
		
		if(isset($data['email'])) $mail->setFromEmail($data['email']);
		if(isset($data['name'])) $mail->setFromName($data['name']);

		$mail->setType('text');//'html' or 'text'
		?>
		<?php if(!isset($data['email'])): ?>
		<ul class="messages"><li class="error-msg"><ul><li><span>Error: No Data.</span></li></ul></li></ul>
		<?php elseif($mail->send()): ?>
		<ul class="messages"><li class="success-msg"><ul><li><span>Your request has been sent.</span></li></ul></li></ul>
		<?php else: ?>
		<ul class="messages"><li class="error-msg"><ul><li><span>Error: Unable to send. Please try again or contact site administrator.</span></li></ul></li></ul>
		<?php endif; ?>
		
	
	<?php } ?>
	
	<?php if($error): ?>
	<ul class="messages"><li class="error-msg"><ul><li><span>Error: <?php print $error?>.</span></li></ul></li></ul>
	<?php endif; ?>
	<div class="buttons-set">
	    <p class="back-link"><a href="<?php echo Mage::helper('cms/page')->getPageUrl('contact-us') ?>"><small>&laquo; </small>Back</a></p>
		<p><a href="<?php echo Mage::helper('core/url')->getHomeUrl();?>">Continue</a></p>
	</div>

<?php endif;?>
