
<div class="container-fluid home-page-content">
    <div class="row">
        <div class="col-md-3">
            <?php echo $this->getChildHtml('topMenu') ?>            
        </div>
        <div class="col-md-9">
            <div class="row visible-md visible-lg">                
                <div class="col-xs-6">
                    <img src="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/home/homeImg2.jpg" class="img-responsive" alt="MBE MRO Home image 2 secure">
                </div>
                <div class="col-xs-6">
                    <img src="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/home/homeImg3.jpg" class="img-responsive" alt="MBE MRO Home image 3">
                </div>
            </div>
            <div class="clear"></div>
            <div class="row visible-md visible-lg">
                <div class="col-xs-6">
                    <img src="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/home/homeImg4.jpg" class="img-responsive" alt="MBE MRO Home image 4">
                </div>
                
                <div class="col-xs-6">
                    <img src="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/home/homeImg5.jpg" class="img-responsive" alt="MBE MRO Home image 5">
                </div>
            </div>

            <div class="row text-center visible-xs visible-sm" id="mobile-img">
                <img src="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/home/homeImg5.jpg" class="img-responsive" alt="MBE MRO Home image 5">
                <img src="<?php print Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/home/homeImg5.jpg" class="img-responsive" alt="MBE MRO Home image 5">
            </div>
                    
        </div>
    </div>
    
</div>
