<?php
/**
 *
 * @category    design
 * @package     mbemro_mobile
 * @copyright   Copyright (c) 2014 MBE MRO Catalog (http://www.mbemrocatalog.com)
 * @license     Commercial
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="account-create" id="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Register') ?></h1>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <h2>Privacy Policy</h2>
<?php
    $helper = Mage::helper('cms');
    $source = Mage::getModel('cms/block')->load('privacy-policy-register-account');
    $processor = $helper->getPageTemplateProcessor();
    $html = $processor->filter($source->getContent());
    echo $html;
?>
      </div>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            

            <div class="row content">
                <div class="col-sm-4"><!--personal info -->
                    <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
                    <div class="row">
                        <div class="col-xs-6 col-sm-12">
                            <div class="field name-firstname">
                                <label for="firstname" class="required"><em>*</em><?php echo $this->__('First Name')?></label>
                                <div class="input-box">
                                    <input type="text" id="firstname" name="firstname" value="<?php echo $this->escapeHtml($this->getFormData()->getFirstname()) ?>" title="First Name" maxlength="255" class="input-text required-entry">
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-12">
                            <div class="field name-lastname">
                                <label for="lastname" class="required"><em>*</em><?php echo $this->__('Last Name')?></label>
                                <div class="input-box">
                                    <input type="text" id="lastname" name="lastname" value="<?php echo $this->escapeHtml($this->getFormData()->getLastname()) ?>" title="Last Name" maxlength="255" class="input-text required-entry">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-12">
                            <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-12">
                        <?php if ($this->isNewsletterEnabled()): ?>
                        
                            <div class="row subscribe">
                                <div class="col-xs-4 col-sm-2"><input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" checked="checked" class="checkbox" /></div>
                                <div class="col-xs-8 col-sm-10"><label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label></div>
                            </div>
                                
                        
                        <?php endif ?>
                        </div>
                    </div>

                </div>
                <div class="col-sm-4"><!-- Login info -->
                    <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
                    <div class="row">
                        <div class="col-xs-6 col-sm-12">
                            <div class="field">
                                <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-12">
                            <div class="field">
                                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                                </div>
                            </div>        
                        </div>
                    </div>                    
                    
                </div>
                <div class="col-sm-4"><!--Additional info -->
                    <?php echo $this->getChildHtml('amastycustomerattr_customer_fields'); ?>
                </div>
            </div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

            <div class="row hidden-xs">
                
                <div class="col-xs-4">
                    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                </div>
                <div class="col-xs-8">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button type="submit" title="<?php echo $this->__('Create An Account') ?>" class="btn button btn-create-account"><span><span><?php echo $this->__('Create An Account') ?></span></span></button>
                </div>

            </div>

            <div class="row visible-xs">
                
                <div class="col-xs-6">
                    
                    <button type="button" class="btn button visible-xs" title="<?php echo $this->__('Back') ?>" onclick="window.location='<?php echo $this->escapeUrl($this->getBackUrl()) ?>'"><span><span><?php echo $this->__('Back'); ?></span></span></button>
                </div>
                <div class="col-xs-6">
                    <p class="required hidden-xs"><?php echo $this->__('* Required Fields') ?></p>
                    <button type="submit" title="<?php echo $this->__('Create An Account') ?>" class="btn button btn-create-account"><span><span><?php echo $this->__('Create An Account') ?></span></span></button>
                </div>

            </div>
            
        
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>

                
                
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        jQuery(function(){
            jQuery(window).resize(function(){

                 if(jQuery(this).width() <= 768){
                    jQuery('#account-create').addClass('account-create-mobile');
                 } else {
                    jQuery('#account-create').removeClass('account-create-mobile');
                 }
              })
              .resize();//trigger resize on page load
        });

    //]]>
    </script>
</div>
