<div class="reset-password">

    <div class="page-title">
        <h1><?php echo $this->__('Reset a Password'); ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
        <div class="row">
            <div class="col-xs-12 col-md-5">
                <div class="row content">
                    <h2 class="legend"><?php echo $this->__('Reset your password here.') ?></h2>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <label for="password"><em>*</em><?php echo $this->__('New Password'); ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <label for="confirmation"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <p class="required pull-left"><?php echo $this->__('* Required Fields'); ?></p>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="button pull-right"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
                    </div>

                </div>

            </div>
        </div>

    </form>

</div>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
    jQuery(function(){
        jQuery(window).resize(function(){

            if(jQuery(this).width() <= 768){
                jQuery('.reset-password').addClass('reset-password-mobile');
            } else {
                jQuery('.reset-password').removeClass('reset-password-mobile');
            }
        })
            .resize();//trigger resize on page load
    });

/*]]>*/
</script>
