<?php
/**
 * Mbemro_CustomCatalog index page.
 *
 * @category Mbemro
 * @package Mbemro_CustomCatalog
 * @version 1.0.0
 * @author Sofija Blazevski <sofi@cp-dev.com>
 *
 * @var $this Mbemro_CustomCatalog_Block_Index
 * @var $_helper Mbemro_CustomCatalog_Helper_Catalog
 *
 */
$_helper = $this->helper('customcatalog/catalog');
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('My Catalog') ?></h1>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <h2><?php echo $this->__('Recently purchased') ?></h2>
        <div class="row">
            <div class="col-xs-12">
                No data.
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <h2><?php echo $this->__('Most purchased') ?></h2>
        <div class="row">
            <div class="col-xs-12">
                No data.
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <h2><?php echo $this->__('Recently added to My Catalog') ?></h2>
        <div class="row">
            <div class="col-xs-12">
                No data.
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <h2><?php echo $this->__('Top Categories (per number of orders)') ?></h2>
        <div class="row">
            <div class="col-xs-12">
                No data.
            </div>
        </div>
    </div>
</div>

<div class="row options">
    <div class="col-xs-12 col-sm-6 col-md-4">
        <a href="<?php echo $_helper->getProductListUrl()?>">View products in My Catalog</a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
        <a href="<?php echo $_helper->getSearchUrl() ?>">Search for products</a>
    </div>
</div>
