<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category    design
 * @package     mbemro_mobile
 * @copyright   Copyright (c) 2014 MBE MRO Catalog (http://www.mbemrocatalog.com)
 * @license     Commercial
 */
?>
	<meta charset="utf-8">
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> --><?php //this doesn't pass w3c validator, set via headers in varnish.?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
	<title><?php echo $this->getTitle() ?></title>
	<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
    <meta name="google-site-verification" content="TLy7gN4PUeezdFzzck3dpH-UgFYK9G_8ir0bU58Zm5U" />
	<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
	<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
	<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
	<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/flick/jquery-ui.min.css">

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<script type="text/javascript">
(function() {
    var isBootstrapEvent = false;
    if (window.jQuery) {
        var all = jQuery('*');
        jQuery.each(['hide.bs.dropdown', 
            'hide.bs.collapse', 
            'hide.bs.modal', 
            'hide.bs.tooltip',
            'hide.bs.popover'], function(index, eventName) {
            all.on(eventName, function( event ) {
                isBootstrapEvent = true;
            });
        });
    }
    var originalHide = Element.hide;
    Element.addMethods({
        hide: function(element) {
            if(isBootstrapEvent) {
                isBootstrapEvent = false;
                return element;
            }
            return originalHide(element);
        }
    });
})();
</script>

<script type="text/javascript">
var __dcid = __dcid || [];__dcid.push(["DigiCertClickID_7v-lKzq0", "3", "m", "black", "7v-lKzq0"]);(function(){
var cid=document.createElement("script");cid.async=true;cid.src="//seal.digicert.com/seals/cascade/seal.min.js";var s = document.getElementsByTagName("script");var ls = s[(s.length - 1)];ls.parentNode.insertBefore(cid, ls.nextSibling);}());
</script>
