<?php
/**
 *
 * @category    design
 * @package     mbemro_mobile
 * @copyright   Copyright (c) 2014 MBE MRO Catalog (http://www.mbemrocatalog.com)
 * @license     Commercial
 */
/*
<fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col />
                <col width="1" />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                <col width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                        <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>"></th>
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                        <?php endif ?>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>

                <tfoot>
                    <tr>
                        <td colspan="50" class="a-right">
                            <?php if($this->getContinueShoppingUrl()): ?>
                                <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue-shopping" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                            <?php endif; ?>
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                            <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
        

*/
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart" id="cart">
    <div class="page-title title-buttons content">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <div class="row data-table cart-table visible-xs">
            <div class="col-xs-9"><span class="nobr"><?php echo $this->__('Product Name') ?></span></div>
            <div class="col-xs-3"><?php echo $this->__('Unit Price') ?></div>
        </div>
        <div class="row data-table cart-table hidden-xs">            
            <div class="col-xs-9"><span class="nobr"><?php echo $this->__('Product Name') ?></span></div>
            <div class="col-xs-1"><span class="nobr"><?php echo $this->__('Unit Price') ?></div>
            <div class="col-xs-1"><?php echo $this->__('Qty') ?></div>
            <div class="col-xs-1"><?php echo $this->__('Subtotal') ?></div>
        </div>
        <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
        <div class="row cart-mobile visible-xs visible-sm">
            <div class="col-xs-6">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="btn button btn-continue-shopping" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                <?php endif; ?>
            </div>
            <div class="col-xs-6">
                <?php echo $this->getChildHtml('totals'); ?>
            </div>
        </div>
        <div class="row cart-mobile visible-xs visible-sm">
            <div class="col-xs-6">
                <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="btn button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
            </div>
            <div class="col-xs-6">
                <button type="submit" name="empty_cart_button-mobile" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="btn button btn-empty" id="empty_cart_button-mobile"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
            </div>
        </div>
        <div class="row cart-options hidden-xs hidden-sm">
            <div class="col-xs-12">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="btn button btn-continue-shopping" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                <?php endif; ?>
                <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="btn button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                <button type="submit" name="empty_cart_button" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="btn button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>            
            </div>
        </div>
        <!--[if lt IE 8]>
        <input type="hidden" id="update_cart_action_container" />
        <script type="text/javascript">
        //<![CDATA[
            Event.observe(window, 'load', function()
            {
                // Internet Explorer (lt 8) does not support value attribute in button elements
                $emptyCartButton = $('empty_cart_button');
                $cartActionContainer = $('update_cart_action_container');
                if ($emptyCartButton && $cartActionContainer) {
                    Event.observe($emptyCartButton, 'click', function()
                    {
                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                        $cartActionContainer.setValue('empty_cart');
                    });
                }

            });
        //]]>
        </script>
        <![endif]-->
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('#empty_cart_button').click(setCartAction);
                jQuery('#empty_cart_button-mobile').click(setCartAction);
            });

            function setCartAction(){
                
                    jQuery('#update_cart_action').val(jQuery(this).attr('value'));

            }
            
        </script>
        <input type="hidden" name="update_cart_action" id="update_cart_action" value="" />
        <?php echo $this->getBlockHtml('formkey') ?>
    </form>
    <div class="row cart-collaterals">
        <div class="col-md-3 col-sm-6 col-xs-12"><?php echo $this->getChildHtml('coupon') ?></div>
        <div class="col-md-4 col-sm-6 col-xs-12"><?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?></div>
        <div class="col-md-5 hidden-xs hidden-sm">
            <div class="totals">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                <ul class="checkout-types">
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6"><?php echo $this->getChildHtml('crosssell') ?></div>
        <div class="col-sm-6"><?php echo $this->getChildHtml('checkout.cart.extra') ?></div>
    </div>
    <div class="row visible-xs visible-sm">
        <?php if(!$this->hasError()): ?>
        
        <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <div class="row">
            <?php echo $methodHtml; ?>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <?php endif; ?>
    </div>
    
</div>
<script type="text/javascript">
//<![CDATA[
        jQuery(function(){
            jQuery(window).resize(function(){

                 if(jQuery(this).width() <= 970){
                    jQuery('#cart').addClass('cart-mobile');
                 } else {
                    jQuery('#cart').removeClass('cart-mobile');
                 }
              })
              .resize();//trigger resize on page load
        });

//]]>
</script>
